### ISSUE TITLE
大佬Wellcee 唯心所寓RSShub能否增加地铁或者关键字选项

### ISSUE THREAD

**Issue by ohyoxo** [TonyRL/RSSHub#1098]
### 这是一个什么样的功能？

比如https://rsshub.app/wellcee/rent/北京/西二旗地铁站

### 这个功能可以解决什么问题？

找寻范围更精确

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
This repo is not monitored, please report to upstream repo instead.
