### ISSUE TITLE
请问如何获得YouTube订阅列表的feed？

### ISSUE THREAD

**Issue by realCrush** [TonyRL/RSSHub#360]
### 这是一个什么样的功能？

获取YouTube订阅列表的feed

### 这个功能可以解决什么问题？

获取YouTube订阅列表的feed

### 额外描述

我从RSSHub文档得知您是订阅YouTube列表功能的作者，但我没有找到稍微详细一点的说明文档，非常抱歉在这里提这个issue了。
我想请问一下怎么获取YouTube订阅列表的rss feed呀，我在vercel自建了rsshub的项目，并且对其他feed都是正常工作的，包括bilibili时间线和微博时间线，并且也设置了YouTube API key，但还是无法订阅YouTube的订阅列表，即  https://xxx.app/youtube/subscriptions ，我翻看了GitHub上所有相关issue，似乎都没有详细的解释，并且翻阅了"部署"部分推荐的GitHub gist： https://gist.github.com/Kurukshetran/5904e8cb2361623498481f4a9a1338aa ，但我发现这已经是一个五年前的gist了，和现在的YouTube API管理不太能对应上。
请问大佬能写个step-to-step的步骤，说一下如何获取YouTube时间线的feed吗？这确实困扰我非常久了，网络上对YouTube API的相关介绍也不多，非常抱歉麻烦您

报错如图：
![image](https://user-images.githubusercontent.com/57980447/175518838-921c4d29-68af-4f09-982a-25cbfbdbba02.png)

关键是YouTube API 的 OAuth 2.0 客户端相关的东西我毫无头绪。。。

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
This [gist](https://gist.github.com/Kurukshetran/5904e8cb2361623498481f4a9a1338aa) is what I followed  when developing `/youtube/subscriptions/:embed?`. You will be fine if you follow it step by step, .
A guide written in 6 years ago doesn't mean it's outdated.
